// src/app/lib/universities.ts

export const UNIVERSITY_LIST_VN: string[] = [
  "Đại học Quốc gia Hà Nội",
  "Đại học Quốc gia TP.HCM",
  "Đại học Đà Nẵng",
  "Đại học Huế",
  "Đại học Thái Nguyên",
  "Đại học Bách khoa Hà Nội",
  "Trường Đại học Kinh tế Quốc dân",
  "Trường Đại học Ngoại thương",
  "Trường Đại học Y Hà Nội",
  "Trường Đại học Thương mại",
  "Trường Đại học Sư phạm Hà Nội",
  "Trường Đại học Xây dựng Hà Nội",
  "Trường Đại học Giao thông Vận tải",
  "Trường Đại học Thủy lợi",
  "Học viện Ngân hàng",
  "Học viện Tài chính",
  "Học viện Bưu chính Viễn thông",
  "Học viện Ngoại giao",
  "Học viện Báo chí và Tuyên truyền",
  "Trường Đại học Công nghiệp Hà Nội",
  "Trường Đại học Bách khoa (Đại học Đà Nẵng)",
  "Trường Đại học Kinh tế (Đại học Đà Nẵng)",
  "Trường Đại học Ngoại ngữ (Đại học Đà Nẵng)",
  "Trường Đại học Sư phạm (Đại học Đà Nẵng)",
  "Trường Đại học Y Dược (Đại học Huế)",
  "Trường Đại học Khoa học (Đại học Huế)",
  "Trường Đại học Vinh",
  "Trường Đại học Nha Trang",
  "Trường Đại học Quy Nhơn",
  "Trường Đại học Tây Nguyên",
  "Trường Đại học Đà Lạt",
  "Trường Đại học Bách khoa (ĐHQG TP.HCM)",
  "Trường Đại học Khoa học Tự nhiên (ĐHQG TP.HCM)",
  "Trường Đại học Khoa học Xã hội và Nhân văn (ĐHQG TP.HCM)",
  "Trường Đại học Công nghệ Thông tin (ĐHQG TP.HCM)",
  "Trường Đại học Quốc tế (ĐHQG TP.HCM)",
  "Trường Đại học Kinh tế TP.HCM",
  "Trường Đại học Y Dược TP.HCM",
  "Trường Đại học Y Khoa Phạm Ngọc Thạch",
  "Trường Đại học Kiến trúc TP.HCM",
  "Trường Đại học Tôn Đức Thắng",
  "Trường Đại học Sư phạm Kỹ thuật TP.HCM",
  "Trường Đại học Công nghiệp TP.HCM",
  "Trường Đại học Ngân hàng TP.HCM",
  "Trường Đại học Luật TP.HCM",
  "Trường Đại học RMIT Việt Nam (Cơ sở Nam Sài Gòn)",
  "Trường Đại học FPT ",
  "Trường Đại học Nguyễn Tất Thành",
  "Trường Đại học Công nghệ TP.HCM",
  "Trường Đại học Cần Thơ"
];