// src/app/lib/universities.ts

export const UNIVERSITY_LIST_VN: string[] = [
  "Đại học Quốc gia Hà Nội",
  "Trường Đại học Công nghệ (ĐHQG Hà Nội)",
  "Trường Đại học Khoa học Tự nhiên (ĐHQG Hà Nội)",
  "Trường Đại học Khoa học Xã hội và Nhân văn (ĐHQG Hà Nội)",
  "Trường Đại học Ngoại ngữ (ĐHQG Hà Nội)",
  "Trường Đại học Kinh tế (ĐHQG Hà Nội)",
  "Trường Đại học Giáo dục (ĐHQG Hà Nội)",
  "Trường Đại học Việt Nhật (ĐHQG Hà Nội)",
  "Trường Đại học Y Dược (ĐHQG Hà Nội)",
  "Trường Đại học Luật (ĐHQG Hà Nội)",
  "Trường Quốc tế (ĐHQG Hà Nội)",
  "Đại học Quốc gia TP.HCM",
  "Trường Đại học Bách khoa (ĐHQG TP.HCM)",
  "Trường Đại học Khoa học Tự nhiên (ĐHQG TP.HCM)",
  "Trường Đại học Khoa học Xã hội và Nhân văn (ĐHQG TP.HCM)",
  "Trường Đại học Công nghệ Thông tin (ĐHQG TP.HCM)",
  "Trường Đại học Quốc tế (ĐHQG TP.HCM)",
  "Trường Đại học Kinh tế - Luật (ĐHQG TP.HCM)",
  "Trường Đại học An Giang (ĐHQG TP.HCM)",
  "Đại học Đà Nẵng",
  "Trường Đại học Bách khoa (Đại học Đà Nẵng)",
  "Trường Đại học Kinh tế (Đại học Đà Nẵng)",
  "Trường Đại học Ngoại ngữ (Đại học Đà Nẵng)",
  "Trường Đại học Sư phạm (Đại học Đà Nẵng)",
  "Trường Đại học Sư phạm Kỹ thuật (Đại học Đà Nẵng)",
  "Trường Đại học Công nghệ Thông tin và Truyền thông Việt - Hàn",
  "Đại học Huế",
  "Trường Đại học Khoa học (Đại học Huế)",
  "Trường Đại học Sư phạm (Đại học Huế)",
  "Trường Đại học Y Dược (Đại học Huế)",
  "Trường Đại học Nông Lâm (Đại học Huế)",
  "Trường Đại học Nghệ thuật (Đại học Huế)",
  "Trường Đại học Kinh tế (Đại học Huế)",
  "Trường Đại học Ngoại ngữ (Đại học Huế)",
  "Trường Đại học Luật (Đại học Huế)",
  "Đại học Thái Nguyên",
  "Trường Đại học Kỹ thuật Công nghiệp (Đại học Thái Nguyên)",
  "Trường Đại học Sư phạm (Đại học Thái Nguyên)",
  "Trường Đại học Nông Lâm (Đại học Thái Nguyên)",
  "Trường Đại học Y Dược (Đại học Thái Nguyên)",
  "Trường Đại học Khoa học (Đại học Thái Nguyên)",
  "Trường Đại học Kinh tế và Quản trị Kinh doanh (Đại học Thái Nguyên)",
  "Trường Đại học Công nghệ Thông tin và Truyền thông (Đại học Thái Nguyên)",
  "Trường Ngoại ngữ (Đại học Thái Nguyên)",
  "Đại học Bách khoa Hà Nội",
  "Đại học Kinh tế Quốc dân",
  "Đại học Kinh tế TP.HCM",
  "Đại học Duy Tân",
  "Trường Đại học Ngoại thương",
  "Trường Đại học Thương mại",
  "Trường Đại học Kinh tế Kỹ thuật Công nghiệp",
  "Trường Đại học Công nghiệp Hà Nội",
  "Trường Đại học Công nghiệp Việt Trì",
  "Trường Đại học Công nghiệp Quảng Ninh",
  "Trường Đại học Điện lực",
  "Trường Đại học Mỏ - Địa chất",
  "Trường Đại học Giao thông Vận tải",
  "Trường Đại học Giao thông Vận tải TP.HCM",
  "Trường Đại học Xây dựng Hà Nội",
  "Trường Đại học Kiến trúc Hà Nội",
  "Trường Đại học Thủy lợi",
  "Trường Đại học Tài nguyên và Môi trường Hà Nội",
  "Trường Đại học Tài nguyên và Môi trường TP.HCM",
  "Trường Đại học Công đoàn",
  "Trường Đại học Lao động - Xã hội",
  "Trường Đại học Nội vụ Hà Nội",
  "Trường Đại học Mở Hà Nội",
  "Trường Đại học Hà Nội",
  "Trường Đại học Sư phạm Hà Nội",
  "Trường Đại học Sư phạm Hà Nội 2",
  "Trường Đại học Thủ đô Hà Nội",
  "Trường Đại học Văn hóa Hà Nội",
  "Trường Đại học Mỹ thuật Công nghiệp",
  "Trường Đại học Mỹ thuật Việt Nam",
  "Trường Đại học Sân khấu - Điện ảnh Hà Nội",
  "Trường Đại học Văn hóa Nghệ thuật Quân đội",
  "Học viện Ngân hàng",
  "Học viện Tài chính",
  "Học viện Công nghệ Bưu chính Viễn thông",
  "Học viện Ngoại giao",
  "Học viện Báo chí và Tuyên truyền",
  "Học viện Chính sách và Phát triển",
  "Học viện Phụ nữ Việt Nam",
  "Học viện Thanh thiếu niên Việt Nam",
  "Học viện Nông nghiệp Việt Nam",
  "Học viện Y Dược học cổ truyền Việt Nam",
  "Học viện Âm nhạc Quốc gia Việt Nam",
  "Học viện Hành chính Quốc gia",
  "Trường Đại học Y Hà Nội",
  "Trường Đại học Dược Hà Nội",
  "Trường Đại học Y tế Công cộng",
  "Trường Đại học Kỹ thuật Y tế Hải Dương",
  "Trường Đại học Điều dưỡng Nam Định",
  "Trường Đại học Y Dược Thái Bình",
  "Trường Đại học Y Dược Hải Phòng",
  "Trường Đại học Sư phạm Kỹ thuật Hưng Yên",
  "Trường Đại học Tài chính - Quản trị Kinh doanh",
  "Trường Đại học Hàng hải Việt Nam",
  "Trường Đại học Hạ Long",
  "Trường Đại học Sao Đỏ",
  "Trường Đại học Hải Dương",
  "Trường Đại học Hoa Lư",
  "Trường Đại học Hồng Đức",
  "Trường Đại học Vinh",
  "Trường Đại học Hà Tĩnh",
  "Trường Đại học Quảng Bình",
  "Trường Đại học Quảng Nam",
  "Trường Đại học Phạm Văn Đồng",
  "Trường Đại học Quy Nhơn",
  "Trường Đại học Phú Yên",
  "Trường Đại học Nha Trang",
  "Trường Đại học Khánh Hòa",
  "Trường Đại học Đà Lạt",
  "Trường Đại học Tây Nguyên",
  "Trường Đại học Buôn Ma Thuột",
  "Trường Đại học Phan Thiết",
  "Trường Đại học Yersin Đà Lạt",
  "Trường Đại học Kinh tế TP.HCM",
  "Trường Đại học Sài Gòn",
  "Trường Đại học Sư phạm TP.HCM",
  "Trường Đại học Sư phạm Kỹ thuật TP.HCM",
  "Trường Đại học Y Dược TP.HCM",
  "Trường Đại học Y Khoa Phạm Ngọc Thạch",
  "Trường Đại học Mỹ thuật TP.HCM",
  "Trường Đại học Sân khấu - Điện ảnh TP.HCM",
  "Trường Đại học Văn hóa TP.HCM",
  "Trường Đại học Luật TP.HCM",
  "Trường Đại học Ngân hàng TP.HCM",
  "Trường Đại học Tài chính - Marketing",
  "Trường Đại học Công Thương TP.HCM",
  "Trường Đại học Công nghiệp TP.HCM",
  "Trường Đại học Mở TP.HCM",
  "Trường Đại học Nông Lâm TP.HCM",
  "Trường Đại học Tôn Đức Thắng",
  "Trường Đại học Công nghệ TP.HCM",
  "Trường Đại học Nguyễn Tất Thành",
  "Trường Đại học Văn Lang",
  "Trường Đại học Hoa Sen",
  "Trường Đại học Quốc tế Hồng Bàng",
  "Trường Đại học Gia Định",
  "Trường Đại học Văn Hiến",
  "Trường Đại học Công nghệ Sài Gòn",
  "Trường Đại học Hùng Vương TP.HCM",
  "Trường Đại học Kinh tế - Tài chính TP.HCM",
  "Trường Đại học Ngoại ngữ - Tin học TP.HCM",
  "Trường Đại học Quản lý và Công nghệ TP.HCM",
  "Trường Đại học RMIT Việt Nam",
  "Trường Đại học FPT",
  "Trường Đại học Greenwich Việt Nam",
  "Trường Đại học Fulbright Việt Nam",
  "Trường Đại học Swinburne Việt Nam",
  "Trường Đại học Việt Đức",
  "Trường Đại học Quốc tế Miền Đông",
  "Trường Đại học Thủ Dầu Một",
  "Trường Đại học Bình Dương",
  "Trường Đại học Lạc Hồng",
  "Trường Đại học Đồng Nai",
  "Trường Đại học Công nghệ Đồng Nai",
  "Trường Đại học Công nghệ Miền Đông",
  "Trường Đại học Bà Rịa - Vũng Tàu",
  "Trường Đại học Dầu khí Việt Nam",
  "Trường Đại học Cần Thơ",
  "Trường Đại học Nam Cần Thơ",
  "Trường Đại học Tây Đô",
  "Trường Đại học Kỹ thuật - Công nghệ Cần Thơ",
  "Trường Đại học Cửu Long",
  "Trường Đại học Trà Vinh",
  "Trường Đại học Đồng Tháp",
  "Trường Đại học An Giang",
  "Trường Đại học Kiên Giang",
  "Trường Đại học Tiền Giang",
  "Trường Đại học Bạc Liêu",
  "Trường Đại học Sư phạm Kỹ thuật Vĩnh Long",
  "Trường Đại học Võ Trường Toản",
  "Trường Đại học Tân Tạo",
  "Trường Đại học Kinh tế Công nghiệp Long An",
  "Trường Đại học Phan Châu Trinh",
  "Trường Đại học Đông Á",
  "Trường Đại học Duy Tân",
  "Trường Đại học Nam Á",
  "Trường Đại học FPT Đà Nẵng",
  "Trường Đại học Kiến trúc Đà Nẵng",
  "Trường Đại học Mỹ tại Việt Nam",
  "Trường Đại học Phú Xuân",
  "Trường Đại học Thái Bình Dương",
  "Trường Đại học Kinh tế Nghệ An",
  "Trường Đại học Công nghệ Vạn Xuân",
  "Trường Đại học Thành Đô",
  "Trường Đại học Đại Nam",
  "Trường Đại học Thăng Long",
  "Trường Đại học Phenikaa",
  "Trường Đại học FPT Hà Nội",
  "Trường Đại học VinUni",
  "Trường Đại học Anh quốc Việt Nam",
  "Trường Đại học CMC",
  "Trường Đại học Mỹ thuật Công nghiệp Á Châu",
  "Trường Đại học RMIT Việt Nam (Cơ sở Hà Nội)",
  "Trường Đại học RMIT Việt Nam (Cơ sở Nam Sài Gòn)",
  "Trường Đại học Kinh doanh và Công nghệ Hà Nội",
  "Trường Đại học Công nghệ Đông Á",
  "Trường Đại học Nguyễn Trãi",
  "Trường Đại học Hòa Bình",
  "Trường Đại học Đông Đô",
  "Trường Đại học Quốc tế Bắc Hà",
  "Trường Đại học Lương Thế Vinh",
  "Trường Đại học Chu Văn An",
  "Trường Đại học Trưng Vương",
  "Trường Đại học Thành Tây",
  "Trường Đại học Công nghệ và Quản lý Hữu nghị",
  "Trường Đại học Tài chính - Ngân hàng Hà Nội",
  "Trường Đại học Công nghệ Giao thông Vận tải",
  "Trường Đại học Lâm nghiệp",
  "Trường Đại học Lâm nghiệp (Phân hiệu Đồng Nai)",
  "Trường Đại học Văn hóa, Thể thao và Du lịch Thanh Hóa",
  "Trường Đại học Sư phạm Kỹ thuật Nam Định",
  "Trường Đại học Kinh Bắc",
  "Trường Đại học Công nghệ và Quản lý Hải Phòng",
  "Trường Đại học Quốc tế Sài Gòn",
  "Trường Đại học Hùng Vương",
  "Trường Đại học Việt Trì",
  "Trường Đại học Tân Trào",
  "Trường Đại học Tây Bắc",
  "Trường Đại học Hải Phòng",
  "Trường Đại học Bắc Kạn",
  "Trường Đại học Thể dục Thể thao Bắc Ninh",
  "Trường Đại học Thể dục Thể thao Đà Nẵng",
  "Trường Đại học Thể dục Thể thao TP.HCM",
  "Trường Đại học Nguyễn Huệ",
  "Trường Đại học Trần Quốc Tuấn",
  "Học viện Kỹ thuật Quân sự",
  "Học viện Quân y",
  "Học viện Khoa học Quân sự",
  "Học viện Biên phòng",
  "Học viện Hải quân",
  "Học viện Phòng không - Không quân",
  "Học viện Cảnh sát Nhân dân",
  "Học viện An ninh Nhân dân",
  "Trường Đại học Cảnh sát Nhân dân",
  "Trường Đại học An ninh Nhân dân",
  "Trường Đại học Phòng cháy Chữa cháy",
  "Trường Đại học Kỹ thuật - Hậu cần Công an Nhân dân",
  "Trường Đại học Kiểm sát Hà Nội",
  "Trường Đại học Luật Hà Nội",
  "Trường Đại học Kiến trúc TP.HCM",
  "Trường Đại học Kỹ thuật Công nghệ Cần Thơ"
];
